INSERT INTO "ToolDefinition" ("id", "key", "name", "description", "icon", "kind", "authType", "documentationUrl", "credentialFields", "endpoint", "httpMethod", "timeoutMs", "encryptedHeaders", "enabled", "requiresApproval", "createdAt", "updatedAt") VALUES
('connector_qcc', 'qichacha', '企查查', '企业工商、股东结构、经营风险和司法信息查询。', 'building-2', 'CONNECTOR', 'API_KEY', 'https://openapi.qcc.com/', '[{"key":"apiKey","label":"API Key","type":"password","required":true,"location":"header","target":"X-Api-Key"}]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_tyc', 'tianyancha', '天眼查', '企业信息、工商登记和经营风险查询。', 'landmark', 'CONNECTOR', 'API_KEY', 'https://open.tianyancha.com/', '[{"key":"token","label":"Token","type":"password","required":true,"location":"header","target":"Authorization"}]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_notn', 'notion', 'Notion', '读取和维护用户授权的 Notion 页面与数据库。', 'notebook-tabs', 'CONNECTOR', 'OAUTH2', 'https://developers.notion.com/docs/authorization', '[]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_gws', 'google-workspace', 'Google Workspace', '访问用户授权的 Google Drive、Docs、Sheets 和 Calendar。', 'google', 'CONNECTOR', 'OAUTH2', 'https://developers.google.com/identity/protocols/oauth2', '[]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_dingtalk', 'dingtalk', '钉钉', '访问用户授权的钉钉组织、文档、消息和日程能力。', 'message-circle', 'CONNECTOR', 'OAUTH2', 'https://open.dingtalk.com/document/', '[]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_wecom', 'wecom', '企业微信', '访问企业微信通讯录、消息和客户联系能力。', 'messages-square', 'CONNECTOR', 'OAUTH2', 'https://developer.work.weixin.qq.com/', '[]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_feishu', 'feishu', '飞书', '访问用户授权的飞书文档、表格、日历和消息。', 'send', 'CONNECTOR', 'OAUTH2', 'https://open.feishu.cn/document/', '[]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_txdoc', 'tencent-docs', '腾讯文档', '访问用户授权的腾讯文档和在线表格。', 'file-text', 'CONNECTOR', 'OAUTH2', 'https://docs.qq.com/open/', '[]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_wps', 'wps-docs', '金山文档', '访问用户授权的 WPS 和金山文档。', 'file-spreadsheet', 'CONNECTOR', 'OAUTH2', 'https://open.wps.cn/', '[]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_stripe', 'stripe', 'Stripe', '查询和管理用户授权的 Stripe 客户、订单与支付数据。', 'credit-card', 'CONNECTOR', 'API_KEY', 'https://docs.stripe.com/keys', '[{"key":"apiKey","label":"Secret Key","type":"password","required":true,"location":"header","target":"Authorization","prefix":"Bearer "}]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_hubspot', 'hubspot', 'HubSpot', '访问用户授权的 HubSpot CRM 联系人和交易数据。', 'contact', 'CONNECTOR', 'OAUTH2', 'https://developers.hubspot.com/docs/guides/apps/authentication/oauth-quickstart-guide', '[]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_gaode', 'amap', '高德地图', '地点搜索、地址解析、路线规划和位置服务。', 'map', 'CONNECTOR', 'API_KEY', 'https://lbs.amap.com/api/webservice/guide/create-project/get-key', '[{"key":"apiKey","label":"Web 服务 Key","type":"password","required":true,"location":"query","target":"key"}]', '', 'GET', 45000, '', false, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_txmap', 'tencent-map', '腾讯地图', '地点搜索、地址解析和路线服务。', 'map-pin', 'CONNECTOR', 'API_KEY', 'https://lbs.qq.com/service/webService/webServiceGuide/webServiceKey', '[{"key":"apiKey","label":"开发者 Key","type":"password","required":true,"location":"query","target":"key"}]', '', 'GET', 45000, '', false, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_trip', 'trip', 'Trip.com', '航班、酒店和旅行信息服务。', 'plane', 'CONNECTOR', 'API_KEY', 'https://www.trip.com/', '[{"key":"apiKey","label":"API Key","type":"password","required":true,"location":"header","target":"X-Api-Key"}]', '', 'GET', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_gamma', 'gamma', 'Gamma', '根据主题创建演示文稿和视觉文档。', 'presentation', 'CONNECTOR', 'API_KEY', 'https://developers.gamma.app/', '[{"key":"apiKey","label":"API Key","type":"password","required":true,"location":"header","target":"X-API-KEY"}]', '', 'POST', 60000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('connector_jinshuju', 'jinshuju', '金数据', '创建、读取和管理表单及数据。', 'clipboard-list', 'CONNECTOR', 'API_KEY', 'https://help.jinshuju.net/', '[{"key":"apiKey","label":"API Key","type":"password","required":true,"location":"header","target":"Authorization"}]', '', 'POST', 45000, '', false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
