packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  core-js: true
  es5-ext: true
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - element-plus@2.14.6

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - es5-ext
  - esbuild
  - vue-demi
